FROM php:8.5-fpm

# System dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    libpq-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
    pdo \
    pdo_pgsql \
    pgsql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/laravel

COPY backend/composer.json backend/composer.lock ./

COPY backend/ .

RUN composer install --optimize-autoloader

RUN composer dump-autoload --optimize

RUN chown -R www-data:www-data /var/www/laravel/storage /var/www/laravel/bootstrap/cache

EXPOSE 8000

# Use artisan serve instead of php-fpm
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]